#!/usr/bin/env python
"""analyze_h12_auc.py -- the H1.2' contrast, with an estimator verified before it is pre-registered.

THE CLAIM
    H1.2': the confidence gate becomes MORE discriminative under noise. The estimand is the WITHIN-ARM AUC
    between correct and incorrect trials - the probability that a randomly chosen correct trial carries
    higher confidence than a randomly chosen incorrect trial, computed separately in each arm. The
    hypothesis is AUC(lambda_mid) > AUC(0).

WHY THIS ESTIMATOR, AND WHY IT NEEDS NO SECOND FRAMEWORK
    A within-arm AUC is a rank statistic, so it is invariant to any monotone transform of `c`. That matters
    here because the library itself warns that this checkpoint's confidence is uncalibrated on an absolute
    scale; an estimand that never reads an absolute threshold cannot be broken by a monotone miscalibration,
    whereas an equivalence bound on a rate at a fixed tau can.

    The design is paired at the ITEM level: every item carries one clean and one noisy observation, each with
    its own (confidence, correctness). Under the null that noise does not change that joint distribution, the
    two arm labels WITHIN an item are exchangeable. So the exact permutation distribution is generated by
    independently swapping each item's two observations, and the test reuses the same within-item
    exchangeability argument as section 4.5's paired permutation. IT DOES NOT NEED A SECOND ESTIMATOR.

WHAT IS CHECKED HERE
    The contrast on real dev trials, the permutation p-value, and - because a permutation test is only exact
    if the statistic is computed the same way under permutation as it is on the data - a positive control
    (a synthetic arm effect must be detected) and a negative control (arm labels shuffled at the item level
    and then reassigned, so the true contrast is zero, must not be detected).

EXIT
  0  computed.  A p below 0.05 is a dev finding, NOT a confirmatory result.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import random
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
TRIALS = REPO_ROOT / "measurement" / "out" / "dev_trials_3seed.jsonl"
RNG_SEED = 20261005
N_PERM = 5000      # p resolution 2e-4, which is ample; keeps the control suite fast


def auc(correct: list[float], incorrect: list[float]) -> float:
    """P(correct > incorrect) + 0.5 P(tie), by the rank statistic. Invariant to monotone transforms."""
    if not correct or not incorrect:
        return float("nan")
    wins = sum(1 for a in correct for b in incorrect if a > b)
    ties = sum(1 for a in correct for b in incorrect if a == b)
    return (wins + 0.5 * ties) / (len(correct) * len(incorrect))


def contrast(obs: dict[str, tuple[float, int]], arm_a: str, arm_b: str) -> float:
    """AUC(arm_b) - AUC(arm_a) over one assignment of observations to arms."""
    by = {arm_a: ([], []), arm_b: ([], [])}      # (correct confidences, incorrect confidences)
    for key, (c, e) in obs.items():
        arm = key.split("|")[0]
        by[arm][e].append(c)
    return auc(*by[arm_b]) - auc(*by[arm_a])


def main() -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").split("\n")[0])
    ap.add_argument("--trials", default=str(TRIALS))
    ap.add_argument("--arm-a", default="0.0")
    ap.add_argument("--arm-b", default="0.18")
    args = ap.parse_args()

    path = pathlib.Path(args.trials)
    if not path.exists():
        print(f"  [FAIL] no trial file at {path}")
        return 1

    # group into exchangeable units: (item, noise_seed) carries ONE observation per arm. The seed is part of
    # the unit because a given item under a given seed is one draw; pooling across seeds would silently treat
    # three draws of the same item as independent items.
    items: dict[str, list[tuple[str, float, int]]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        if r.get("status") != "ok" or r.get("question_id") != "intent":
            continue
        lam = str(r["lambda"])
        if lam not in (args.arm_a, args.arm_b):
            continue
        items.setdefault(f"{r['item_id']}|s{r['noise_seed']}", []).append(
            (lam, float(r["c"]), int(r["error"])))

    pairs = {k: v for k, v in items.items() if len(v) == 2}
    print(f"  exchangeable units (item x seed) with one observation in each arm: {len(pairs)}")
    print(f"    distinct items: {len({k.split(chr(124))[0] for k in pairs})}")
    if len(pairs) < 20:
        print("  [FAIL] too few complete pairs to test")
        return 1

    # observed
    # THE UNIT KEY MUST BE PART OF EVERY OBSERVATION KEY. Enumerating within the unit and flattening collides
    # - every unit produces a key like "0.0|0" - and the whole dataset collapses to two observations, which is
    # exactly what an earlier draft of this script did while still printing a p-value.
    obs = {k: {lam: (c, e) for (lam, c, e) in v} for k, v in pairs.items()}
    flat = {f"{lam}|{k}": ce for k, d in obs.items() for lam, ce in d.items()}
    t_obs = contrast(flat, args.arm_a, args.arm_b)
    for arm in (args.arm_a, args.arm_b):
        cs = [c for k, (c, e) in flat.items() if k.startswith(arm) and e == 0]
        es = [c for k, (c, e) in flat.items() if k.startswith(arm) and e == 1]
        print(f"    arm=lambda {arm}: n_correct={len(cs)}, n_error={len(es)}, AUC={auc(cs, es):.4f}")
    if len(flat) != 2 * len(pairs):
        print(f"  [FAIL] {len(flat)} flattened observations for {len(pairs)} units x 2 arms - the unit key is"
              f" not unique in the observation keys, so the statistic is not computed over the data")
        return 1
    print(f"  observed contrast AUC(lambda {args.arm_b}) - AUC(lambda {args.arm_a}) = {t_obs:+.4f}")

    # exact paired permutation: independently swap each item's two observations
    keys = sorted(pairs)
    rnd = random.Random(RNG_SEED)
    hits = 0
    for _ in range(N_PERM):
        perm = {}
        for k in keys:
            a, b = obs[k][args.arm_a], obs[k][args.arm_b]
            if rnd.random() < 0.5:
                a, b = b, a
            perm[f"{args.arm_a}|{k}"] = a
            perm[f"{args.arm_b}|{k}"] = b
        if contrast(perm, args.arm_a, args.arm_b) >= t_obs:
            hits += 1
    p = (hits + 1) / (N_PERM + 1)
    print(f"  one-sided paired permutation p = {p:.5f}   ({N_PERM} permutations, {hits} at least as extreme)")

    # POSITIVE CONTROL: force an arm effect by shifting the noisy arm's errors down
    ctrl = {}
    for k in keys:
        a = obs[k][args.arm_a]
        c, e = obs[k][args.arm_b]
        ctrl[f"{args.arm_a}|{k}"] = a
        # SHIFT ONLY THE ERROR TRIALS. An earlier draft shifted the whole arm by a constant, which is a
        # monotone transform of the arm and therefore leaves a within-arm AUC EXACTLY unchanged - the control
        # was inert and printed the observed contrast back as if it had passed. A positive control has to
        # move the quantity the hypothesis is about.
        ctrl[f"{args.arm_b}|{k}"] = (max(0.0, c - 0.25), e) if e == 1 else (c, e)
    t_ctrl = contrast(ctrl, args.arm_a, args.arm_b)
    print(f"  POSITIVE CONTROL (noisy arm ERROR trials shifted down, correct trials untouched): "
          f"contrast {t_ctrl:+.4f}")
    print(f"      observed {t_obs:+.4f} -> control {t_ctrl:+.4f}  "
          f"{'DETECTED, the statistic moves in the hypothesised direction' if t_ctrl > t_obs else 'NOT DETECTED'}")
    if not t_ctrl > t_obs:
        print("  [FAIL] the positive control is inert, so the p-value below cannot be trusted")
        return 1

    # NEGATIVE CONTROL: assign arms at random, so the true contrast is zero
    rnd2 = random.Random(RNG_SEED + 1)
    nulls = []
    for _ in range(20):
        nc = {}
        for k in keys:
            a, b = obs[k][args.arm_a], obs[k][args.arm_b]
            if rnd2.random() < 0.5:
                a, b = b, a
            nc[f"{args.arm_a}|{k}"] = a
            nc[f"{args.arm_b}|{k}"] = b
        nulls.append(contrast(nc, args.arm_a, args.arm_b))
    print(f"  NEGATIVE CONTROL (random arm assignment): contrast over 20 draws "
          f"mean {sum(nulls)/len(nulls):+.4f}, range [{min(nulls):+.4f}, {max(nulls):+.4f}]"
          f"  -> {'centred on zero' if abs(sum(nulls)/len(nulls)) < 0.02 else 'BIASED'}")

    # THE DATASET LABEL IS DERIVED FROM THE FILE, NEVER ASSUMED. An earlier version of this script printed
    # "Dev only. NOT a confirmatory result" unconditionally, so feeding it the confirmatory record still
    # reported the finding as dev work - the most dangerous kind of mislabel, because it understates a
    # confirmatory result rather than overstating it, and nothing downstream would catch the difference.
    stem = path.stem.lower()
    if "confirm" in stem:
        label = "CONFIRMATORY (the test split; this is a confirmatory result)"
    elif "dev" in stem:
        label = "DEV (non-confirmatory; the test split is untouched)"
    else:
        label = f"UNLABELLED input ({path.name}) - treat as non-confirmatory until you know"

    if p < 0.05 and t_obs > 0:
        print(f"\n  [OK] H1.2' contrast is positive and significant. Estimator: the exact within-unit paired")
        print(f"       permutation of section 4.5 - no second inferential framework is required.")
    else:
        print(f"\n  [NOTE] the contrast does not reach the direction-and-significance bar.")
    print(f"  Dataset: {label}")
    return 0


if __name__ == "__main__":
    sys.exit(main())