#!/usr/bin/env python
"""assemble_supplementary_information.py -- build the SI from its parts, in the journal's order.

WHY AN ASSEMBLER RATHER THAN ONE BIG GENERATOR
    The first SI was generated by a script that held its prose inline, which made the document a by-product of
    the code and left it reading like an engineering log. The sections are now AUTHORED FILES under docs/si/,
    written as prose and reviewed as prose, and this script only puts them in order and adds the parts that
    genuinely are derived: the contents page, the registration table (read from the protocol's own frozen
    checklist), the figure plate (read from the figure pipeline's caption file) and the reference list.

WHAT IS DERIVED AND WHAT IS AUTHORED
    Authored:    docs/si/A..E  - the narrative sections.
    Derived:     the contents, the registration table (protocol section 12), the figure plate (caption file +
                 PNGs), and the references appendix, which is carried forward from the previous SI because it
                 was already assembled from sources rather than from memory.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SI_DIR = ROOT / "docs" / "si"
PROTOCOL = ROOT / "protocol" / "NHB_Orthographic_Channels_JEV_Research_Protocol.md"
FIG_CAPTIONS = ROOT / "viz" / "figures" / "FIGURE_CAPTIONS.md"
FIG_DIR = ROOT / "viz" / "figures"
PREV = ROOT / "docs" / "SUPPLEMENTARY_INFORMATION.md"
OUT = ROOT / "docs" / "SUPPLEMENTARY_INFORMATION.md"

SECTION_ORDER = [
    ("A", "A_background_and_design.md", "Background and design"),
    ("B", "B_formal_framework.md", "Formal framework"),
    ("C", "C_stimuli_and_instrument.md", "Stimuli, noise model and instrument"),
    ("D", "D_analysis_power_and_results.md", "Analysis, power and results"),
    ("E", "E_interpretation_and_reproducibility.md", "Interpretation, limitations and reproduction"),
    # The era section carries the title's own frame, so it precedes the outward generalisation: what this
    # means where the study lives, then what it means to fields that do not share its setting.
    ("F", "F_llm_era_significance.md", "Significance in the age of large language models"),
    ("G", "G_multidisciplinary_significance.md", "Significance across disciplines"),
    ("H", "H_registration.md", "Pre-registration: the frozen checklist"),
    ("I", "I_references.md", "References"),
]

FIGURES = [
    ("fig1_stage2_hypotheses", "The three pre-registered hypotheses across the noise grid"),
    ("fig2_stage2_error_destination", "Where the errors go: the gate rejects most of what noise breaks"),
    ("fig3_stage2_gate_separation", "Why the gate separates better under noise"),
    ("fig4_stage2_scale_free", "The scale-free property, measured on the confirmatory record"),
    ("fig5_stage2_proof_graph", "The proof dependency graph, parsed from the kernel source"),
    ("fig6_stage2_corrections",
     "The formalisation corrected the protocol, and the corrections were kept"),
    ("fig7_stage2_evidence_chain", "What the manuscript's claims rest on"),
    ("fig8_stage2_failure_partition",
     "The failure-class partition, drawn on the two diagnostics that separate the classes"),
]


def registration_table() -> str:
    """Appendix F: the protocol's frozen checklist, read from the protocol rather than restated.

    A registration table typed by hand is a second copy of the protocol that can disagree with it. This reads
    the checklist out of the protocol itself, so the SI cannot claim a frozen value the protocol does not carry.
    """
    text = PROTOCOL.read_text(encoding="utf-8")
    m = re.search(r"^## 12\..*?^\| # \|.*?\n((?:^\|[^\n]*\n)+)", text, re.S | re.M)
    out = ["## H. Pre-registration: the frozen checklist", "",
           "The values below are read from the protocol's own checklist rather than restated, so this table "
           "cannot claim a frozen value the protocol does not carry.", ""]
    if not m:
        out.append("*The protocol's checklist could not be read; this is reported rather than silently omitted.*")
        return "\n".join(out) + "\n"
    # THE ROWS ALREADY CARRY THEIR LEADING PIPE. Prefixed with another, every row began "| | 1 | … |", the
    # first cell parsed as the EMPTY STRING, and `set("") <= set("-: ")` is TRUE - the empty set is a subset of
    # everything - so every row was discarded as the separator and the assembled SI shipped a registration
    # table with a header and no body. The separator test now requires a NON-EMPTY first cell, because "empty
    # passes the test" is the same defect as "an empty Counter reported zero duplicates as a finding": a check
    # that a missing value satisfies is not a check.
    rows = [l for l in m.group(1).strip().splitlines() if l.strip("| ")]
    out.append("| Item | Requirement | State |")
    out.append("|---|---|---|")
    for r in rows:
        cells = [c.strip() for c in r.strip().strip("|").split("|")]
        first = cells[0] if cells else ""
        if len(cells) >= 3 and first and set(first) <= set("-: "):
            continue                       # a separator row, identified by a non-empty dash-or-colon first cell
        if len(cells) >= 3:
            out.append("| " + " | ".join(cells[:3]) + " |")
    out.append("")
    return "\n".join(out) + "\n"


def figure_plate() -> str:
    """The figures with their captions, inserted where a reader expects them: after the results."""
    if not FIG_CAPTIONS.exists():
        return ""
    caps = {m.group(1): m.group(2).strip()
            for m in re.finditer(r"^## (\S+)\n\n(.*?)(?=\n## |\Z)",
                                 FIG_CAPTIONS.read_text(encoding="utf-8"), re.S | re.M)}
    # A plate, not a numbered section: it carries no letter in the contents, exactly like "Contents" itself,
    # so it cannot collide with the A-H sequence however that sequence changes.
    out = ["## Figures", ""]
    for i, (stem, title) in enumerate(FIGURES, start=1):
        if stem not in caps or not (FIG_DIR / f"{stem}.png").exists():
            continue
        cap = re.sub(r"\*\*(.+?)\*\*", r"**\1**", caps[stem])
        out += [f"**Figure {i}. {title}.**", "", f"![Figure {i}](figures/{stem}.png)", "", cap, ""]
    return "\n".join(out) + "\n" if len(out) > 2 else ""


def main() -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").split("\n")[0])
    args = ap.parse_args()

    # the previous SI carries the references appendix, assembled from sources; preserve it
    refs = ""
    if PREV.exists():
        t = PREV.read_text(encoding="utf-8")
        m = re.search(r"^## Appendix J.*?(?=\n## |\Z)", t, re.S | re.M)
        if m:
            refs = re.sub(r"^## Appendix J.*?\n", "## I. References\n", m.group(0), count=1, flags=re.S)

    parts = ["# Supplementary information", "",
             "**LIMEN Phase I — orthographic channels and input noise as structural disturbances in human–model "
             "interaction in the age of large language models**", "",
             "*Supplementary information provided by the authors; not edited.*", "",
             # A standfirst, so the finding is visible before the appendices begin. Everything below elaborates
             # this sentence, and a reader who stops here should still have the result.
             "**The result in one sentence.** Typing errors cost a language model accuracy and coverage, yet the "
             "confidence gate that decides whether to answer becomes *sharper* under them — the errors arrive "
             "below the gate rather than above it — so in the age of language models the damage from the input "
             "channel lands on what the system declines to answer, not on what it commits to.", "",
             "---", "", "## Contents", ""]
    body: list[str] = []

    have = []
    for letter, fname, title in SECTION_ORDER:
        p = SI_DIR / fname
        if p.exists():
            body.append(p.read_text(encoding="utf-8").rstrip() + "\n")
            have.append((letter, title))
        elif fname == "H_registration.md":
            body.append(registration_table())
            have.append((letter, title))
        elif fname == "I_references.md":
            if refs:
                body.append(refs.rstrip() + "\n")
                have.append((letter, title))
    for letter, title in have:
        parts.append(f"**{letter}.** {title}")
    parts += ["", "---", ""]
    # The spine goes first: everything else elaborates it.
    spine = SI_DIR / "T_thesis_gap_contribution.md"
    if spine.exists():
        parts.append(spine.read_text(encoding="utf-8").rstrip() + "\n")
        parts.append("---")
        parts.append("")


    # The plate sits AFTER the results and BEFORE the interpretation: a reader should meet the figures their
    # own text points at, not arrive at them past a discussion that already assumes them.
    plate = figure_plate()
    assembled: list[str] = []
    for block in body:
        if block.lstrip().startswith("## E. ") and plate:
            assembled.append(plate)
        assembled.append(block)
    parts += assembled

    OUT.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8", newline="\n")
    words = len(OUT.read_text(encoding="utf-8").split())
    print(f"  wrote {OUT.relative_to(ROOT)}  ({OUT.stat().st_size // 1024} KB, {words} words)")
    print(f"  sections: {', '.join(l for l, _ in have)}")
    print(f"  figure plate: {'included' if plate else 'MISSING'}")
    math = len(re.findall(r"(?<!\$)\$(?!\$)", OUT.read_text(encoding="utf-8"))) // 2
    print(f"  inline math spans: {math}")
    return 0


if __name__ == "__main__":
    sys.exit(main())