#!/usr/bin/env python
"""build_provenance_table.py -- derive a claim-by-claim provenance table and write it into the protocol.

WHY THIS EXISTS
    The protocol now contains four kinds of statement, and until this table existed a reader could not
    tell them apart: (i) facts the kernel proved, (ii) premises the design takes as given, (iii) empirical
    claims the run will test, and (iv) claims that are none of those but read as though they were. A
    formalisation that is cited in the prose but not mapped to the claims makes the whole document look
    machine-checked, which is worse than not having it. This table is the map.

THE RULE THAT MAKES IT MORE THAN DOCUMENTATION
    A row marked PROVED must name a theorem that actually exists in the kernel-verified set. If it does
    not, this script FAILS rather than writing the row. So the table cannot drift into claiming proofs
    that were never done - the failure mode the project has already hit once, when a status record
    overstated a theorem count and nothing but a hand-written guard noticed.

WHAT NO ROW MAY SAY
    No row is marked PROVED if what it asserts is that noise changes Accuracy, SilentError or Coverage.
    Those are the empirical claims, and by construction no theorem can prove them: they are stated as a
    named premise in §4.4 and tested by the run. `check` mode enforces that no such row appears as PROVED,
    because "the formalisation proves the hypothesis" is the one misreading this table exists to prevent.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
LEAN_ROOT = REPO_ROOT.parent / "lean-nhb"
PROTOCOL = REPO_ROOT / "protocol" / "NHB_Orthographic_Channels_JEV_Research_Protocol.md"

BEGIN = "<!-- PROVENANCE:BEGIN - generated by scripts/build_provenance_table.py; do not edit by hand -->"
END = "<!-- PROVENANCE:END -->"

# (claim as the protocol states it, status, authority, note)
#   status: PROVED   -> `authority` must be one or more theorem names in the kernel-verified set
#           ASSUMED  -> a premise the design takes as given; `authority` is where it is recorded
#           TESTED   -> an empirical claim the run will decide; `authority` is where it is registered
CLAIMS: list[tuple[str, str, str, str]] = [
    # ---- proved, and each name is checked against the kernel ----
    ("`SilentError@τ` is non-increasing in τ", "PROVED", "risk_mono",
     "§6 stated the opposite until the kernel refuted it"),
    ("`Coverage@ε` is non-increasing in τ", "PROVED", "coverage_mono",
     "the tie-break's premise, machine-checked"),
    ("raising τ can only discard accepted trials", "PROVED", "accepted_mono",
     "the gate cannot un-reject"),
    ("admissibility is monotone in τ", "PROVED", "admissible_mono",
     "used by the tie-break proof"),
    ("a least admissible threshold exists", "PROVED", "admissible_exists, top_admissible",
     "§B1 needs existence before it can prefer one"),
    ("the least admissible threshold maximises coverage among admissible ones", "PROVED",
     "least_admissible_maximises_coverage, least_admissible_is_at_least_as_good",
     "§B1, and the reason the rule reads LEAST"),
    ("an empty dev set is degenerate, not neutral", "PROVED", "empty_dev_is_degenerate",
     "every τ admissible and coverage zero"),
    ("for small dev sets, ε = 0.05 drives the least admissible τ to close every gate", "PROVED",
     "budget_collapses_to_zero_on_small_dev",
     "first end of the degeneracy spectrum"),
    ("immediately below the limen the gate keeps only the error", "PROVED",
     "the_threshold_below_the_limen_keeps_only_the_error",
     "the opposite end of the same spectrum"),
    ("§6's original 'non-decreasing in τ' wording is false", "PROVED", "protocol_said_nondecreasing_is_FALSE",
     "kept as evidence that the feedback loop ran"),
    ("`Acc` read as defers-counted-as-errors is non-increasing in τ", "PROVED", "acc_defers_wrong_mono",
     "why §3.4's fixed τ cannot be tuned away"),
    ("`Acc` cannot separate 'understood less' from 'committed less'", "PROVED",
     "acc_is_not_diagnostic_of_understanding, one_movement_three_readings",
     "the H1.1 correction"),
    ("§6.1's `CondErr` and `CondAcc` are one quantity", "PROVED", "cond_error_complements_cond_accuracy",
     "the declared dependency in the confirmatory family"),
    ("at the clean end the fitted selector returns a design constant", "PROVED",
     "clean_pins_at_floor, delta_tau_reduces_to_the_noisy_selector",
     "the §4.4a correction"),
    ("the set of thresholds consistent with the dev data is exactly an interval from the limen up",
     "PROVED", "admissible_iff_limen_le",
     "the exact interval §4.4a reports in place of a bootstrap"),
    ("`Δτ* = 0` does not identify 'no disturbance'", "PROVED", "same_diagnostic_from_different_arms",
     "tolerance-absorbed disturbance reports identically"),

    # ---- assumed: premises the design takes as given ----
    ("the gate commits on `argmax p`", "ASSUMED", "§3.4",
     "a definitional choice; a different rule would move every number"),
    ("`c = max_j p_j` is comparable across conditions", "ASSUMED", "§3.3",
     "a calibration assumption about the instrument, not a theorem"),
    ("λ acts only through the text channel", "ASSUMED", "§2, §3.2",
     "if noise also perturbed the encoder internals the channel reading would need restating"),
    ("`τ*` fitted on dev transfers to test", "ASSUMED", "§6/v1.2 CHANGE 3",
     "dev and test are disjoint by item; transfer is a premise, not a result"),
    ("`intent` alone captures Q0", "ASSUMED", "v1.2 CHANGE 1",
     "`ok` and `escalate` were dropped after measuring at chance"),
    ("the generator is keyboard-faithful and λ controls the rate", "ASSUMED", "§3.2, `N_en` implementation",
     "a construction property, checkable by inspection rather than by the kernel"),

    # ---- tested: the run decides these, and no theorem can ----
    ("H1.1 — `Acc(λ_mid) < Acc(0)`", "TESTED", "§4.4; co-reported with `CondAcc`",
     "no theorem can prove it; that is why it is the empirical claim"),
    ("H1.2 — `SilentError@0.9(λ_mid) > SilentError@0.9(0)`", "TESTED", "§4.4; co-primary", ""),
    ("H1.3 — coverage falls, or `CondErr@τ` rises", "TESTED", "§4.4; co-primary",
     "disjunct 2 is not independent evidence for H1.1"),
    ("`Δτ* > 0` — the fitted limen moves under noise", "TESTED", "§4.4a; reported, not confirmatory",
     "usually unattainable when the clean arm sits at the floor"),
    ("the Phase II cross-script law", "TESTED", "§4.4 H2.1–H2.2", "reserved for Phase II"),
    ("the λ rates are readable at the intended level", "TESTED", "O1, Amendment 3 v3",
     "closed by rule: λ_lo = 0.05 and λ_mid = 0.18 selected against the published Rayner (2006) anchor"),
]

STATUS_MARK = {"PROVED": "**PROVED**", "ASSUMED": "*ASSUMED*", "TESTED": "**TO BE TESTED**"}


def verified_theorems() -> set[str]:
    """Names the kernel actually checked. Source of truth is the Lean file plus a clean axiom run."""
    src = (LEAN_ROOT / "NHB" / "PhaseI" / "Core.lean").read_text(encoding="utf-8")
    names = set(re.findall(r"^theorem\s+(\w+)", src, re.M))
    proc = subprocess.run([sys.executable, "-B", str(REPO_ROOT / "scripts" / "check_lean_axioms.py")],
                          capture_output=True, text=True, cwd=REPO_ROOT, timeout=600)
    m = re.search(r"OK: (\d+) theorem\(s\)", proc.stdout)
    if proc.returncode != 0 or not m:
        raise SystemExit("the kernel axiom check did not pass - refusing to publish a provenance "
                         "table over an unverified formalisation\n" + (proc.stdout + proc.stderr)[:600])
    checked = int(m.group(1))
    if checked != len(names):
        raise SystemExit(f"the kernel checked {checked} theorems but the source declares {len(names)}; "
                         "resolve that before publishing the table")
    return names


def build_table(theorems: set[str]) -> str:
    missing: list[str] = []
    for claim, status, authority, _ in CLAIMS:
        if status != "PROVED":
            continue
        for name in [a.strip() for a in authority.split(",")]:
            if name not in theorems:
                missing.append(f"{claim!r} cites {name!r}, which is not a verified theorem")
    if missing:
        print("FAIL: a claim is marked PROVED against a theorem that does not exist.")
        for m in missing:
            print("  -", m)
        print("\nA proof that was never done is the one thing this table must not contain.")
        sys.exit(1)

    lines = [
        BEGIN,
        "",
        "### 12.1 Claim provenance — what is proved, what is assumed, what is tested",
        "",
        f"Generated by `scripts/build_provenance_table.py` from the kernel-verified set of "
        f"**{len(theorems)} theorems**. A row marked **PROVED** names a theorem the kernel checked; the "
        f"generator fails if such a theorem does not exist, so this table cannot claim a proof that was "
        f"never done. **No row here is marked PROVED for a statement that noise changes Accuracy, "
        f"SilentError or Coverage** — those are the empirical claims, and no theorem can settle them.",
        "",
        "| Claim as the protocol states it | Status | Authority | Note |",
        "|---|---|---|---|",
    ]
    for claim, status, authority, note in CLAIMS:
        auth = f"`{authority}`" if status == "PROVED" else authority
        lines.append(f"| {claim} | {STATUS_MARK[status]} | {auth} | {note} |")
    counts = {s: sum(1 for _, st, _, _ in CLAIMS if st == s) for s in ("PROVED", "ASSUMED", "TESTED")}
    lines += [
        "",
        f"**{counts['PROVED']} proved · {counts['ASSUMED']} assumed · {counts['TESTED']} to be tested.** "
        f"The third column is the whole point: a reader can see which conclusions rest on the kernel, "
        f"which on a premise the design chose, and which on the run that has not happened yet.",
        "",
        END,
    ]
    return "\n".join(lines)


def negative_test() -> int:
    """Inject a claim that is PROVED against a theorem that does not exist, and require a failure.

    A generator that only ever succeeds is not a check. This control asserts the property the table
    exists for: a claimed proof that was never done must stop the build. The injected name is real-looking
    on purpose - a typo of an actual theorem is the shape this defect would take in practice.
    """
    global CLAIMS
    original = CLAIMS
    try:
        CLAIMS = original + [("(negative control) an invented claim", "PROVED",
                              "risk_mono_but_actually_does_not_exist", "injected")]
        try:
            build_table(verified_theorems())
        except SystemExit as exc:
            if exc.code == 1:
                print("  negative control: the generator refused an unproved claim  OK")
                return 0
            print(f"  negative control: exited {exc.code} rather than 1")
            return 1
        print("  negative control FAILED: an unproved claim was accepted into the table")
        return 1
    finally:
        CLAIMS = original


def main() -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="verify the protocol's table matches the derived truth; write nothing")
    ap.add_argument("--negative-test", action="store_true",
                    help="inject an unproved claim and require the generator to refuse it")
    args = ap.parse_args()

    if args.negative_test:
        return negative_test()

    text = PROTOCOL.read_text(encoding="utf-8")
    new_block = build_table(verified_theorems())

    if BEGIN not in text or END not in text:
        if args.check:
            print("FAIL: the protocol has no provenance block to check.")
            return 1
        anchor = "## 13."
        i = text.find(anchor)
        if i < 0:
            raise SystemExit("cannot find the insertion anchor ('## 13.') in the protocol")
        text = text[:i] + new_block + "\n\n---\n\n" + text[i:]
        PROTOCOL.write_text(text, encoding="utf-8", newline="\n")
        print("  provenance table inserted into the protocol")
        return 0

    i = text.find(BEGIN)
    j = text.find(END, i) + len(END)
    current = text[i:j]
    if current == new_block:
        print(f"  OK: provenance table is current "
              f"({len(CLAIMS)} claims, all PROVED rows name verified theorems)")
        return 0
    if args.check:
        print("FAIL: the provenance table in the protocol does not match the derived truth.")
        cur_lines, new_lines = current.splitlines(), new_block.splitlines()
        for k in range(max(len(cur_lines), len(new_lines))):
            a = cur_lines[k] if k < len(cur_lines) else "<absent>"
            b = new_lines[k] if k < len(new_lines) else "<absent>"
            if a != b:
                print(f"  first difference at line {k + 1}:\n    in protocol: {a[:110]}\n    derived    : {b[:110]}")
                break
        return 1

    text = text[:i] + new_block + text[j:]
    PROTOCOL.write_text(text, encoding="utf-8", newline="\n")
    print("  provenance table refreshed in the protocol")
    return 0


if __name__ == "__main__":
    sys.exit(main())