#!/usr/bin/env python
"""build_proof_appendix.py -- derive a machine-checked core section and write it into the protocol.

WHY THIS EXISTS, AND WHY IT IS NOT §4.4b
    §4.4b records WHAT the machine check changed: seven corrections, each a place a proof contradicted a
    sentence the protocol had already written. §12.1 records which claim rests on which theorem. Neither
    shows the PROOF ITSELF - the statements that were checked, grouped as they are grouped in the source,
    and the procedure that checked them. A reader who wants to know whether a claim is load-bearing or
    decorative has to open the Lean file, which is exactly the position the provenance table exists to
    avoid.

    The HTML is the deliverable and also the first thing to iterate. So the proof process is iterated into
    it: theorem, statement, and what each one bears on, generated from the source rather than transcribed.

THE TWO CHECKS THAT MAKE THIS MORE THAN A LISTING
    1. The theorem-to-claim map must be a BIJECTION. A theorem with no declared bearing fails the build,
       because an undeclared theorem is a proof nobody has decided the meaning of; a declared theorem
       that does not exist also fails. Keeping the map complete is therefore not a matter of diligence.
    2. Every statement is extracted from the Lean source by a bracket-depth scan for the `:=` that opens
       the proof, not by a regex over lines. Theorems here span several lines and contain `:=` inside
       their own bodies (`AccDefersWrong : Nat -> List Obs -> Nat | _, [] => 0 | ...`), so a line-based
       pattern silently truncates or over-reads. A truncated statement in a proof appendix is worse than
       no appendix.

WHAT THIS FILE DOES NOT CLAIM
    It does not claim the statements are interesting, or that proving them was hard. It reports what the
    kernel accepted. Whether a theorem bears on the right question is a judgement, and it is recorded as
    a judgement in the `bears on` column, not derived.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
LEAN_ROOT = REPO_ROOT.parent / "lean-nhb"
CORE = LEAN_ROOT / "NHB" / "PhaseI" / "Core.lean"
PROTOCOL = REPO_ROOT / "protocol" / "NHB_Orthographic_Channels_JEV_Research_Protocol.md"

BEGIN = "<!-- PROOF-APPENDIX:BEGIN - generated by scripts/build_proof_appendix.py; do not edit by hand -->"
END = "<!-- PROOF-APPENDIX:END -->"

# theorem -> (what it bears on, the protocol section it audits). MUST cover every theorem exactly once.
BEARS_ON: dict[str, tuple[str, str]] = {
    "silent_iff_acceptedAndWrong":
        ("`SilentError@τ` and the accepted-error rate are ONE count, not two", "§6"),
    "accepted_mono":
        ("a stricter gate cannot un-reject a trial - the premises of every monotonicity below", "§3.4"),
    "coverage_mono":
        ("`Coverage@ε` falls as τ rises: the tie-break's premise", "§6"),
    "risk_mono":
        ("`SilentError@τ` is NON-INCREASING in τ - §6 said the opposite", "§6 — v1.3 CHANGE 2"),
    "admissible_mono":
        ("admissibility is upward closed, so the admissible set is an interval", "§6.1"),
    "mem_maxC":
        ("a threshold above the largest confidence admits nothing - the search bound", "§6/v1.2 CHANGE 3"),
    "top_admissible":
        ("the top of the grid is always admissible, so a limen always exists", "§6/v1.2 CHANGE 3"),
    "admissible_exists":
        ("existence, needed before §B1 can prefer one threshold to another", "Amendment 2 §B1"),
    "coverage_decreases":
        ("the tie-break buys coverage at the limen, stated as a loss above it", "Amendment 2 §B1"),
    "protocol_said_nondecreasing_is_FALSE":
        ("§6's original wording, kept as the evidence that the feedback loop ran", "§4.4b"),
    "least_admissible_maximises_coverage":
        ("LEAST is optimal, not merely conventional - the reason the rule reads that way",
         "Amendment 2 §B1"),
    "least_admissible_is_at_least_as_good":
        ("the same optimality from the other side, so the rule is not direction-sensitive",
         "Amendment 2 §B1"),
    "empty_dev_is_degenerate":
        ("an empty dev set makes every threshold admissible and coverage zero", "§6"),
    "budget_collapses_to_zero_on_small_dev":
        ("for N < 20 the ε=0.05 budget is 0, so the least admissible τ closes every gate", "§6"),
    "the_threshold_below_the_limen_keeps_only_the_error":
        ("immediately below the limen the gate retains the error and nothing else - the opposite "
         "degeneracy", "§6"),
    "acc_is_not_diagnostic_of_understanding":
        ("`Acc` falls while accuracy conditional on committing rises, on IDENTICAL answer-correctness",
         "§6 — v1.4 CHANGE 1"),
    "acc_defers_wrong_mono":
        ("under defers-as-errors `Acc` is non-increasing in τ, and §3.4 fixes τ", "§4.4 H1.1"),
    "cond_error_complements_cond_accuracy":
        ("H1.3's \"error among accepted\" is the COMPLEMENT of the H1.1 co-report - one quantity, so not "
         "independent evidence", "§4.5 — v1.5"),
    "one_movement_three_readings":
        ("one confidence movement drives `Acc` down, `CondErr` down and `CondAcc` up simultaneously",
         "§6.1"),
    "clean_pins_at_floor":
        ("with a clean arm at the floor the selector returns a DESIGN CONSTANT for every ε",
         "§4.4a — v1.6 CHANGE 1"),
    "delta_tau_reduces_to_the_noisy_selector":
        ("so `Δτ*` is one estimate minus a constant, not two estimates", "§4.4a — v1.6 CHANGE 1"),
    "same_diagnostic_from_different_arms":
        ("`Δτ* = 0` cannot distinguish no disturbance from a tolerance-absorbed one",
         "§4.4a — v1.6 CHANGE 1"),
    "admissible_iff_limen_le":
        ("τ is admissible IFF τ ≥ τ*, so the interval §4.4a reports is EXACTLY writable down - which is "
         "why the bootstrap was withdrawn", "§4.4a — v1.8 CHANGE 1"),
}

SECTION_TITLES = {
    "The feedback loop: a sentence in the manuscript, refuted by the kernel":
        "§6's direction, refuted",
    "Amendment 2 section B1, machine-checked in full":
        "Amendment 2 §B1, in full",
    "The degenerate cases, named rather than averaged away":
        "degeneracy, named rather than averaged",
    "The feedback loop: a fitted threshold the protocol did not anticipate":
        "the budget collapse",
    "The feedback loop: `Acc` as §6 defines it, audited against the gate":
        "eq (7), audited against the gate",
    "The feedback loop: `Δτ*` as §4.4a reports it":
        "§4.4a's diagnostic",
    "The feedback loop: §4.4a's bootstrap interval, replaced by an exact one":
        "§4.4a's interval, made exact",
    "": "definitions and the gate's monotonicity",
}


def parse_core() -> list[dict]:
    """Return [{name, statement, section}] in source order."""
    text = CORE.read_text(encoding="utf-8")
    sections = [(m.start(), re.sub(r"\s+", " ", m.group(1)).strip())
                for m in re.finditer(r"/-!\s*#+\s*(.*?)\s*-/", text, re.S)]
    out = []
    for m in re.finditer(r"^theorem\s+(\w+)", text, re.M):
        name, after = m.group(1), m.end()
        i, depth = after, 0
        stmt = ""
        while i < len(text) - 1:
            ch = text[i]
            if ch in "([{":
                depth += 1
            elif ch in ")]}":
                depth -= 1
            elif ch == ":" and text[i:i + 2] == ":=" and depth == 0:
                stmt = " ".join(text[after:i].split())
                break
            i += 1
        if not stmt:
            raise SystemExit(f"could not find the proof opening for `{name}`; refusing to publish a "
                             f"truncated statement in a proof appendix")
        section = next((nm for pos, nm in reversed(sections) if pos < m.start()), "")
        out.append({"name": name, "statement": stmt, "section": section})
    return out


def build() -> str:
    thms = parse_core()
    names = {t["name"] for t in thms}

    undeclared = sorted(names - set(BEARS_ON))
    phantom = sorted(set(BEARS_ON) - names)
    problems = []
    if undeclared:
        problems.append("PROVED BUT UNDECLARED (a proof nobody decided the meaning of): "
                        + ", ".join(undeclared))
    if phantom:
        problems.append("DECLARED BUT ABSENT (the appendix would cite a proof that does not exist): "
                        + ", ".join(phantom))
    if problems:
        print("FAIL: the theorem-to-claim map is not a bijection.")
        for p in problems:
            print("  -", p)
        print("\nThe map is complete by construction or the build stops.")
        sys.exit(1)

    grouped: dict[str, list[dict]] = {}
    for t in thms:
        grouped.setdefault(t["section"], []).append(t)

    L = [
        BEGIN,
        "",
        "## 15. Machine-checked core",
        "",
        "**This section is generated from the Lean source, not transcribed from it.** Every statement below "
        "was extracted from the source by a bracket-depth scan and every theorem named here was verified by "
        "the kernel (`#print axioms`) to depend on no `sorry`. The generator fails the build if a theorem "
        "has no declared bearing below, or if a bearing cites a theorem that does not exist, so the table "
        "cannot quietly acquire a proof that was never done or lose one that was.",
        "",
        f"**{len(thms)} theorems, zero errors, zero `sorry`.** The permitted axioms are `propext`, "
        "`Quot.sound` and `Classical.choice` - the last being Lean's classical logic, not a gap in a proof.",
        "",
        "**How the check runs, and why it is trusted.** Three things had to hold before any of these "
        "statements could be used to correct the protocol: (1) the kernel query returns a `#print axioms` "
        "line for every theorem, and an empty answer *raises* rather than passing - because absent output "
        "reads exactly like \"axiom-free\"; (2) a negative control injects a `sorry`-proved theorem into "
        "the real file, rebuilds, and requires the check to catch it; (3) a freshness guard re-derives "
        "every theorem and line count from the source so a stale number in a document cannot survive. "
        "Without (2) and (3) the first check is a green light with nothing behind it.",
        "",
        "**The correction record in §4.4b was produced by this machinery, not confirmed by it.** Each of "
        "the seven entries there is a place where a machine-checked statement contradicted a sentence the "
        "protocol had already written - a direction, an optimality claim, a degeneracy, a domain of "
        "definition, a family's dependence structure, an endpoint's identifiability, and a reporting "
        "procedure. So the table below is the evidence for §4.4b, and §4.4b is the interpretation of it.",
        "",
    ]
    for section, items in grouped.items():
        title = SECTION_TITLES.get(section, section or "unnamed section")
        L += [f"**{title}**", "",
              "| Theorem | Statement | What it bears on | Section |", "|---|---|---|---|"]
        for t in items:
            bears, sec = BEARS_ON[t["name"]]
            stmt = t["statement"].replace("|", "\\|")
            if len(stmt) > 210:
                stmt = stmt[:207] + "…"
            L.append(f"| `{t['name']}` | `{stmt}` | {bears} | {sec} |")
        L.append("")
    L += [
        "**Authority:** `scripts/check_lean_axioms.py` (kernel query, with a negative control), "
        "`scripts/check_lean_status_freshness.py` (derived counts), "
        "`scripts/build_proof_appendix.py --check` (this section is current, and the map is a bijection).",
        "",
        END,
    ]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").split("\n")[0])
    ap.add_argument("--check", action="store_true", help="verify the section in the protocol is current")
    ap.add_argument("--negative-test", action="store_true",
                    help="inject an undeclared theorem and require the bijection check to refuse it")
    args = ap.parse_args()

    if args.negative_test:
        global BEARS_ON
        saved = dict(BEARS_ON)
        try:
            BEARS_ON.pop("admissible_iff_limen_le", None)
            try:
                build()
            except SystemExit as exc:
                if exc.code == 1:
                    print("  negative control: an undeclared theorem was refused  OK")
                    return 0
                print(f"  negative control: exited {exc.code} rather than 1")
                return 1
            print("  negative control FAILED: a theorem with no declared bearing was accepted")
            return 1
        finally:
            BEARS_ON = saved

    text = PROTOCOL.read_text(encoding="utf-8")
    block = build()

    if BEGIN in text and END in text:
        i = text.find(BEGIN)
        j = text.find(END, i) + len(END)
        current = text[i:j]
        if current == block:
            print(f"  OK: proof appendix is current ({len(parse_core())} theorems, map is a bijection)")
            return 0
        if args.check:
            print("FAIL: the proof appendix in the protocol does not match the Lean source.")
            cur, new = current.splitlines(), block.splitlines()
            for k in range(max(len(cur), len(new))):
                a = cur[k] if k < len(cur) else "<absent>"
                b = new[k] if k < len(new) else "<absent>"
                if a != b:
                    print(f"  first difference at line {k + 1}:\n    in protocol: {a[:100]}\n"
                          f"    derived    : {b[:100]}")
                    break
            return 1
        text = text[:i] + block + text[j:]
        PROTOCOL.write_text(text, encoding="utf-8", newline="\n")
        print("  proof appendix refreshed in the protocol")
        return 0

    if args.check:
        print("FAIL: the protocol has no proof appendix to check.")
        return 1

    anchor = "*End of protocol v"
    k = text.rfind(anchor)
    if k < 0:
        raise SystemExit("cannot find the protocol's end marker to insert before")
    text = text[:k] + block + "\n\n---\n\n" + text[k:]
    PROTOCOL.write_text(text, encoding="utf-8", newline="\n")
    print(f"  proof appendix inserted ({len(parse_core())} theorems, map is a bijection)")
    return 0


if __name__ == "__main__":
    sys.exit(main())