#!/usr/bin/env python
"""build_item_bank.py -- deterministic item-bank builder for Phase I (O3), option C.

OPTION C, AS DIRECTED
    Expand the content space moderately (12 kernels per domain, each with >= 2 fillable slots) so the
    frozen size of 932 is reachable, and MEASURE the homogeneity that expansion creates rather than
    asserting it is harmless. The confound probe is `scripts/template_confound_probe.py`.

GOLD IS A CONSTRUCTION INVARIANT, NOT AN ANNOTATION
    Every item is rendered from a scenario kernel whose domain is known, so `intent_gold` cannot
    disagree with the item's construction and no labeler is involved. A human pass then checks only
    that an item is plausible and unambiguous to a reader -- never what the answer is. This removes the
    pilot's weakest feature (Amendment 1 section A4: gold assigned by the same agent that wrote the
    items, with no human pass).

AMBIGUITY IS A REJECTION, AND IT IS MECHANICAL
    An item generated for domain D is DROPPED if any rival domain's strong anchor appears in its text.
    The anchor sets are small and specific and exclude common co-occurring words (account, card,
    subscription) that would over-reject. `info` is the residual: an info item must contain no anchor.

PROVENANCE
    Templates are authored here. No earlier corpus is used, and nothing is generated by the pinned
    model -- the model is never the question-setter.

DETERMINISM
    Pure function of (size, seed). The dev/test split is by `item_id` hash, so an item sits in the same
    side at every lambda and every noise seed, which is what the within-item design rests on.

TEMPLATE ID
    Every item records `template_id` (domain + kernel index). This is what the confound probe groups
    on, and it is recorded at BUILD time so the probe cannot be accused of reconstructing it after
    seeing accuracy.
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import json
import pathlib
import random
import re
import sys

DOMAINS = ("billing", "access", "urgency", "info")

# --- strong, domain-exclusive anchors; a rival domain's anchor in a D-item is a rejection ----------
ANCHORS = {
    "billing": ("invoice", "refund", "overcharged", "charged twice", "payment failed",
                "charged me", "double charge", "billing charge", "money back", "charged for"),
    "access":  ("password", "sign in", "sign-in", "log in", "login", "locked out", "credentials",
                "two-factor", "reset link", "cannot access", "single sign-on"),
    "urgency": ("outage", "is down", "immediately", "urgent", "asap", "emergency", "deadline is",
                "every request", "all users", "production is", "sev-1", "critical failure",
                "escalate"),
}

SLOTS = {
    "plan":    ("the Pro plan", "the Team plan", "my annual plan", "the monthly plan",
                "my Basic plan", "the premium plan"),
    "month":   ("this month", "last month", "in March", "in April", "this billing cycle", "in May"),
    "amount":  ("$40", "$19", "$120", "$8.50", "$63", "$210"),
    "service": ("the billing page", "the export tool", "the mobile app", "the API gateway",
                "the report viewer", "the settings panel"),
    "team":    ("my team", "our onboarding group", "the finance shared inbox",
                "our workspace", "the support queue", "the design group"),
    "day":     ("tomorrow", "on Friday", "by Monday", "this afternoon", "before the review",
                "before the board meeting"),
    "n":       ("four", "twelve", "thirty", "two hundred", "seventy", "forty"),
    "region":  ("the EU", "the UK", "Singapore", "Brazil", "Canada", "Australia"),
}

# 12 kernels per domain, each with at least two fillable slots.
KERNELS = {
    "billing": [
        "I was charged twice for {plan} {month}. Both charges are on the same card and the second one "
        "was not authorised. Please refund the duplicate charge.",
        "My invoice for {month} shows a {amount} line item I do not recognise. I need it explained and, "
        "if it is wrong, removed from the bill.",
        "I cancelled {plan} last week but {month} I was charged again. Please reverse the renewal and "
        "confirm by email.",
        "I requested a refund for {plan} {month} and it has not appeared on my statement yet. Can you "
        "check where {amount} went?",
        "Please update the card on file for {plan} before the next billing date, which is {day}.",
        "I was charged {amount} for {plan} {month} but my agreement says the price is different. Which "
        "of the two is correct?",
        "I downgraded {plan} before {month} and was charged for the old tier anyway. Please correct the "
        "charge for {amount} and tell me what happens next.",
        "There is a duplicate subscription charge for {plan} on my statement {month}. One of them, for "
        "{amount}, should be removed.",
        "The invoice I received {month} bills {team} for {plan} at {amount}, but that is not our "
        "subscription. Please remove it.",
        "I was charged for {service} {month} although I never subscribed to it. Please refund "
        "{amount} and confirm nothing is scheduled for {day}.",
        "I would like a refund of {amount} covering {n} months of {plan}, because the service was down "
        "for most of that time and I could not use what I paid for.",
        "The price of {plan} rose to {amount} {month} without any notice from me. Please explain the "
        "change and tell me whether I can keep the old rate until {day}.",
    ],
    "access": [
        "I changed phones last week and now I cannot sign in to my account. The password reset email "
        "for {service} never arrives and I am locked out before {day}.",
        "My password for {service} stopped working this morning and the reset link does not arrive for "
        "{team}. I need to get in {day}.",
        "I was removed from {team} by someone else and I can no longer log in to the shared workspace. "
        "Please restore the access I had before {day}.",
        "Two-factor authentication is blocking me from signing in to {service} for {team}. I do not "
        "have my code device with me and I need access {day}.",
        "My login for {service} says my credentials are invalid even though the password is right. "
        "Please check what is wrong with the account for {team}.",
        "I cannot access the billing records on my account {month}. The page says I lack permission "
        "for {team} although I should be able to see them {day}.",
        "Please help me regain access to {service}: the account for {team} is locked and support closed "
        "my last request without an answer.",
        "I share {team} with two colleagues but my role was changed to read-only and I can no longer "
        "log in to the editing tools. Please restore write access {day}.",
        "The account for {team} has been locked for {n} days after I failed to sign in, and the "
        "password reset for {service} never arrives. I am completely stuck.",
        "The password reset email for {service} has not reached {team} at all, so I cannot sign in. "
        "This has been going on since {day}.",
        "I cannot sign in to {service} from {region} since {day}, although the same credentials work "
        "for {team} elsewhere. Please check whether {plan} access is region-limited.",
        "Permissions on the {team} project in {service} were removed by an administrator and now I "
        "cannot log in to edit. I have a deadline {day}.",
    ],
    "urgency": [
        "Our production service is returning errors for every request since 09:15 this morning. "
        "Please escalate this immediately - all users are affected.",
        "{service} is down for everyone on {team} and the deadline is {day}. This is urgent; I need "
        "someone on it now.",
        "This is an emergency: the payment path for {plan} is failing for all users and we are losing "
        "money every minute. Please escalate immediately.",
        "A critical deadline is {day} and {service} has still not deployed the change for {team}. "
        "Please treat this as urgent.",
        "All users of {service} are reporting the same failure right now. It is a sev-1 for us and "
        "needs immediate attention.",
        "We are {day} from a compliance audit and {service} is still broken for {team}. Please "
        "escalate this immediately to whoever can restore it.",
        "{service} went down at 03:00 and nobody has responded for {n} hours. All users are blocked. "
        "Please escalate now.",
        "Production is failing for every request since midnight and {team} cannot reach anyone. This "
        "is urgent - please escalate immediately.",
        "There is an outage on {service} affecting {team} and {n} other groups. Every request fails and "
        "users are calling. Please escalate this now.",
        "Urgent: charges for {plan} have been failing for all users since {day} and nobody has replied "
        "to {team}. Please escalate immediately.",
        "{service} has been returning errors for every request for {n} hours and all users are "
        "blocked. This is urgent and needs immediate escalation.",
        "The deadline is {day} and {service} is still broken for {team}; all users are affected. "
        "Please escalate this now - it cannot wait.",
    ],
    "info": [
        "Could you tell me whether {service} supports single sign-on, and does it work with the shared "
        "accounts {team} uses?",
        "I would like to understand how {plan} is priced. Is the {amount} figure monthly, or does it "
        "cover the whole year?",
        "Does {service} offer a {n}-month option for {team}, and what would {plan} cost on that term?",
        "What happens to my data on {service} if I stop using it for a year, and can I export "
        "everything first?",
        "For a piece I am writing about your service: who founded the company, and in what year? "
        "Nothing is required on my account.",
        "Which regions does {service} run in - {region} specifically - and has that list changed "
        "recently? I only need the information.",
        "How does {service} compare with the two alternatives I am evaluating for {team}? I would like "
        "the main differences before deciding on {plan}.",
        "Is there an academic discount available on {plan}, and what documents do you need? I can send "
        "proof from {team}.",
        "Is there an API for {service}, and what are its rate limits? I am sizing a deployment for "
        "{team} that would make about {n} calls a day.",
        "How do I reach support outside business hours, and is there a {plan}-specific channel that "
        "{team} should use instead?",
        "Does {service} support data residency in {region}, and does choosing {plan} change where "
        "{team}'s data is stored?",
        "What does your documentation say about migrating {team} off {service}, and how long does "
        "that take with {plan}?",
    ],
}

CRITERIA = {
    "billing":  "a request about money: a charge, an invoice, a refund, or a payment method",
    "access":   "a request about getting in: sign-in, a password, a permission, or an account lock",
    "urgency":  "a request that needs immediate action because something is broken now or a deadline "
                "is close",
    "info":     "a request that only asks for information and needs no change to an account",
}


def anchors_of(text: str) -> set:
    t = text.lower()
    out = set()
    for dom, phrases in ANCHORS.items():
        for p in phrases:
            if p in t:
                out.add(dom)
                break
    return out


def is_unambiguous(domain: str, text: str) -> bool:
    return not (anchors_of(text) - {domain})


def build(size: int, seed: int, criteria_mode: str):
    rng = random.Random(seed)
    per = size // len(DOMAINS)
    rem = size - per * len(DOMAINS)
    quota = {d: per + (1 if i < rem else 0) for i, d in enumerate(DOMAINS)}

    n_opts_cycle = (2, 3, 4)
    items, rejected, seen = [], 0, set()
    counters = {d: 0 for d in DOMAINS}

    for domain in DOMAINS:
        kernels = KERNELS[domain]
        attempts, limit = 0, quota[domain] * 600
        while counters[domain] < quota[domain]:
            attempts += 1
            if attempts > limit:
                print(f"    [warn] {domain}: exhausted at {counters[domain]}/{quota[domain]} "
                      f"after {attempts} attempts", file=sys.stderr)
                break
            k_idx = rng.randrange(len(kernels))
            text = kernels[k_idx]
            for _ in range(3):
                text = re.sub(r"\{(\w+)\}", lambda m: rng.choice(SLOTS[m.group(1)]), text)
            if "{" in text:
                continue
            text = " ".join(text.split())
            if not is_unambiguous(domain, text):
                rejected += 1
                continue
            norm = re.sub(r"[^a-z ]", "", text.lower()).strip()
            if norm in seen:
                continue
            seen.add(norm)

            idx = counters[domain]
            counters[domain] += 1
            item_id = f"ph1_{domain}_{idx:04d}"
            n_opt = n_opts_cycle[idx % len(n_opts_cycle)]

            others = [d for d in DOMAINS if d != domain]
            local = random.Random(int(hashlib.sha256(item_id.encode()).hexdigest()[:8], 16))
            options = local.sample(others, n_opt - 1) + [domain]
            local.shuffle(options)

            intent = {"type": "choice",
                      "instructions": "Which category should this request be routed to?",
                      "options": options}
            if criteria_mode == "full":
                intent["criteria"] = {d: CRITERIA[d] for d in options}
            elif criteria_mode != "names":
                raise SystemExit(f"unknown criteria_mode: {criteria_mode}")

            items.append({
                "item_id": item_id,
                "state": text,
                "domain": domain,
                # recorded at BUILD time so the probe cannot reconstruct it after seeing accuracy
                "template_id": f"{domain}:k{k_idx:02d}",
                "intent": intent,
                "intent_gold": domain,
            })

    for it in items:
        h = int(hashlib.sha256(it["item_id"].encode()).hexdigest()[:8], 16)
        it["split"] = "dev" if (h % 100) < 30 else "test"
    return items, rejected


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the Phase I item bank (O3, option C).")
    ap.add_argument("--size", type=int, default=932)
    ap.add_argument("--seed", type=int, default=20261004)
    ap.add_argument("--criteria-mode", choices=("full", "names"), default="full")
    ap.add_argument("--out", default="measurement/item_bank.jsonl")
    ap.add_argument("--manifest", default="measurement/item_bank_manifest.json")
    args = ap.parse_args()

    items, rejected = build(args.size, args.seed, args.criteria_mode)

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8", newline="\n") as fh:
        for it in items:
            fh.write(json.dumps(it, ensure_ascii=False) + "\n")

    by_dom = collections.Counter(i["domain"] for i in items)
    by_split = collections.Counter(i["split"] for i in items)
    by_opts = collections.Counter(len(i["intent"]["options"]) for i in items)
    by_tpl = collections.Counter(i["template_id"] for i in items)
    by_dom_opts = collections.Counter((i["domain"], len(i["intent"]["options"])) for i in items)

    manifest = {
        "bank": str(out).replace("\\", "/"),
        "bank_sha256": hashlib.sha256(out.read_bytes()).hexdigest(),
        "size": len(items),
        "requested_size": args.size,
        "seed": args.seed,
        "criteria_mode": args.criteria_mode,
        "ok_escalate": "DROPPED (Amendment 2 section B4: the noul primitive measured at chance in C2)",
        "gold_provenance": "CONSTRUCTION INVARIANT - not annotation. Each item is rendered from a "
                           "scenario kernel whose domain is known; no labeler is involved.",
        "ambiguity_rule": "an item for domain D is DROPPED if any rival domain's strong anchor appears "
                          "in its text. info is the residual and must contain no anchor.",
        "anchors_rejected_items": rejected,
        "template_id_recorded_at": "BUILD TIME, before any model scored the bank",
        "counts": {
            "per_domain": dict(by_dom),
            "per_split": dict(by_split),
            "per_option_count": dict(by_opts),
            "per_template": dict(by_tpl),
            "per_domain_x_options": {f"{d}|{n}": c for (d, n), c in sorted(by_dom_opts.items())},
        },
        "templates_per_domain": {d: len(KERNELS[d]) for d in DOMAINS},
        "items_per_template_min": min(by_tpl.values()),
        "items_per_template_max": max(by_tpl.values()),
        "chance_accuracy_by_option_count": {n: 1.0 / n for n in by_opts},
        "provenance": "templates authored in scripts/build_item_bank.py. No earlier corpus. "
                      "Not generated by the pinned model.",
    }
    mp = pathlib.Path(args.manifest)
    mp.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")

    print(f"  bank     -> {out}  ({len(items)} items, {out.stat().st_size} B)")
    print(f"  sha256   -> {manifest['bank_sha256']}")
    print(f"  manifest -> {mp}  ({mp.stat().st_size} B)")
    print()
    print(f"  per domain      : {dict(by_dom)}")
    print(f"  per split       : {dict(by_split)}   (30% dev / 70% test)")
    print(f"  per option count: {dict(by_opts)}")
    print(f"  templates/domain: {manifest['templates_per_domain']}")
    print(f"  items/template  : min {manifest['items_per_template_min']} max "
          f"{manifest['items_per_template_max']}  across {len(by_tpl)} templates")
    print(f"  rejected (mechanical ambiguity rule): {rejected}")
    print()
    if len(items) < args.size:
        print(f"  未达标: 目标 {args.size}, 实得 {len(items)}, 缺口 {args.size - len(items)}")
    else:
        print(f"  达标: {len(items)}/{args.size}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())