#!/usr/bin/env python
"""build_item_bank.py -- deterministic item-bank builder for Phase I (O3).

DESIGN CHANGE WORTH READING FIRST
    The pilot's gold was AGENT-ASSIGNED with no human pass, which Amendment 1 §A4 flagged as a
    weakness: if the same agent wrote the items and the labels, they may be self-answering.

    This builder removes that weakness at the root. Every item is RENDERED FROM A SCENARIO KERNEL
    whose domain is known by construction, so `intent_gold` is a **construction invariant, not an
    annotation**. No labeler is involved. A human pass is then needed only to check that each item
    is *plausible and unambiguous to a reader* - never to decide what the answer is.

AMBIGUITY IS A REJECTION, AND IT IS MECHANICAL
    An item generated for domain D must contain no STRONG anchor of any other domain. The anchor
    sets are deliberately small and specific (e.g. "invoice", "password", "outage") and exclude
    common words like "account", "card" or "subscription", which legitimately co-occur across
    domains and would over-reject. `info` is the residual domain: an info item must contain no
    anchor at all. Violations are DROPPED and counted, never repaired.

PROVENANCE
    No item is drawn from, or paraphrased from, any earlier corpus, and none is generated by the
    pinned model - the templates are authored here, so the model is never the question-setter.

DETERMINISM
    Pure function of (bank_size, seed). The split is by `item_id` hash, so an item sits in the same
    side at every lambda and every noise seed - which is what the within-item design rests on.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import random
import re
import sys

DOMAINS = ("billing", "access", "urgency", "info")

# --- strong, domain-exclusive anchors; anything here in a rival domain's item = rejection -------
ANCHORS = {
    "billing":  ("invoice", "refund", "overcharged", "charged twice", "payment failed",
                 "charged me", "double charge", "billing charge", "money back"),
    "access":   ("password", "sign in", "sign-in", "log in", "login", "locked out", "credentials",
                 "two-factor", "reset link", "cannot access"),
    "urgency":  ("outage", "is down", "immediately", "urgent", "asap", "emergency", "deadline is",
                 "every request", "all users", "production is", "sev-1", "critical failure"),
}
# "info" has no anchors of its own: it is the residual, so ANY anchor disqualifies it.

# --- slots --------------------------------------------------------------------------------------
SLOTS = {
    "plan":    ("the Pro plan", "the Team plan", "my annual plan", "the monthly plan",
                "my Basic plan", "the premium plan"),
    "month":   ("this month", "last month", "in March", "in April", "this billing cycle"),
    "amount":  ("$40", "$19", "$120", "$8.50", "$63"),
    "service": ("the billing page", "the export tool", "the mobile app", "the API gateway",
                "the report viewer"),
    "team":    ("my team", "our onboarding group", "the finance shared inbox",
                "our workspace", "the support queue"),
    "day":     ("tomorrow", "on Friday", "by Monday", "this afternoon", "before the review"),
    "n":       ("four", "twelve", "thirty", "two hundred"),
}

# --- scenario kernels: (domain, [format strings]) -------------------------------------------------
KERNELS = {
    "billing": [
        "I was charged twice for {plan} {month}. Both charges are on the same card and the second one "
        "was not authorised. Please refund the duplicate charge.",
        "My invoice for {month} shows a {amount} line item I do not recognise. I need it explained and, "
        "if it is wrong, removed from the bill.",
        "I cancelled {plan} last week but {month} I was charged again. Please reverse the renewal and "
        "confirm by email.",
        "I requested a refund {month} and it has not appeared on my statement yet. Can you check where "
        "it went?",
        "Please update the card on file for {plan} before the next billing date, which is {day}.",
        "The amount charged for {plan} {month} is {amount}, but my agreement says {amount}. Which one "
        "is right?",
        "I have been charged for {plan} {month} although I downgraded before that. Please correct the "
        "charge and tell me what to do next.",
        "There is a duplicate subscription charge for {plan} on my statement {month}. One of them "
        "should be removed.",
    ],
    "access": [
        "I changed phones last week and now I cannot sign in to my account. The password reset email "
        "never arrives and I am locked out before {day}.",
        "My password for {service} stopped working this morning and the reset link does not arrive. I "
        "need to get in {day}.",
        "I was removed from {team} by someone else and I can no longer log in to the shared workspace. "
        "Please restore what I had.",
        "Two-factor authentication is blocking me from signing in to {service}. I do not have my code "
        "device with me and I need access {day}.",
        "My login for {service} says my credentials are invalid even though the password is right. "
        "Please check what is wrong with my account.",
        "I cannot access the billing records on my account {month}. The page says I lack permission "
        "although I should be able to see them.",
        "Please help me regain access to {service}: my account is locked and support closed the last "
        "request without an answer.",
        "I share {team} with two colleagues but my role was changed to read-only and I cannot sign in "
        "to the editing tools any more.",
    ],
    "urgency": [
        "Our production service is returning errors for every request since 09:15 this morning. "
        "Please escalate this immediately - all users are affected.",
        "{service} is down for everyone on {team} and the deadline is {day}. This is urgent; I need "
        "someone on it now.",
        "This is an emergency: the payment path for {plan} is failing for all users and we are losing "
        "money every minute. Please escalate immediately.",
        "A critical deadline is {day} and {service} still has not deployed the change. Please treat "
        "this as urgent.",
        "All users of {service} are reporting the same failure right now. It is a sev-1 for us and "
        "needs immediate attention.",
        "We are {day} from a compliance audit and {service} is still broken. Please escalate this "
        "immediately to whoever can restore it.",
        "{service} went down at 03:00 and nobody has responded for {n} hours. All users are blocked. "
        "Please escalate now.",
        "Production is failing for every request since midnight and our team cannot reach anyone. "
        "This is urgent - please escalate immediately.",
    ],
    "info": [
        "Could you tell me whether {service} supports single sign-on? I am comparing it with another "
        "product and cannot find the answer on the website.",
        "I would like to understand how {plan} is priced. Is the {amount} figure monthly or is it "
        "for the whole year?",
        "What does your support policy say about how long a ticket stays open? I could not find it "
        "stated anywhere.",
        "Can you explain what happens to my data if I stop using {service} for a year? I am weighing "
        "whether to keep it.",
        "I am writing an article about your service and would like to know who founded the company and "
        "when. No action needed on my account.",
        "Please tell me which regions {service} runs in, and whether that list changed recently. I "
        "only need the information.",
        "How does {service} compare with the two alternatives I am evaluating? I would like to know "
        "the main differences before I decide anything.",
        "I would like to know whether there is an academic discount available, and what documents you "
        "need. Nothing else is required from me right now.",
    ],
}


def anchors_of(text: str) -> set:
    t = text.lower()
    found = set()
    for dom, phrases in ANCHORS.items():
        for p in phrases:
            if p in t:
                found.add(dom)
                break
    return found


def is_unambiguous(domain: str, text: str) -> bool:
    """True iff no RIVAL domain's anchor appears."""
    found = anchors_of(text)
    rivals = found - {domain}
    return not rivals


def build(bank_size: int, seed: int, criteria_mode: str, include_extra_questions: bool) -> tuple:
    rng = random.Random(seed)
    per_domain = bank_size // len(DOMAINS)
    remainder = bank_size - per_domain * len(DOMAINS)
    quota = {d: per_domain + (1 if i < remainder else 0) for i, d in enumerate(DOMAINS)}

    # option-count schedule: balanced across 2, 3, 4 so chance accuracy is not constant
    n_opts_cycle = (2, 3, 4)

    items, rejected, seen = [], 0, set()
    counters = {d: 0 for d in DOMAINS}

    for domain in DOMAINS:
        kernels = KERNELS[domain]
        attempts = 0
        while counters[domain] < quota[domain]:
            attempts += 1
            if attempts > quota[domain] * 400:            # safety valve
                print(f"    [warn] {domain}: exhausted uniqueness after {attempts} attempts "
                      f"at {counters[domain]}/{quota[domain]}", file=sys.stderr)
                break
            k = rng.choice(kernels)
            text = k
            # fill every slot that appears
            for _ in range(2):                              # a couple of passes is plenty
                text = re.sub(r"\{(\w+)\}", lambda m: rng.choice(SLOTS[m.group(1)]), text)
            if "{" in text:                                  # a slot name we do not have
                continue
            text = " ".join(text.split())

            if not is_unambiguous(domain, text):
                rejected += 1
                continue
            norm = re.sub(r"[^a-z ]", "", text.lower()).strip()
            if norm in seen:                               # enforce uniqueness
                continue
            seen.add(norm)

            idx = counters[domain]
            counters[domain] += 1
            item_id = f"ph1_{domain}_{idx:04d}"
            n_opt = n_opts_cycle[idx % len(n_opts_cycle)]

            # gold is the construction domain; distractors are the other domains, deterministic
            others = [d for d in DOMAINS if d != domain]
            rng_local = random.Random(int(hashlib.sha256(item_id.encode()).hexdigest()[:8], 16))
            distractors = rng_local.sample(others, n_opt - 1)
            options = distractors + [domain]
            rng_local.shuffle(options)

            if criteria_mode == "full":
                criteria = {d: CRITERIA[d] for d in options}
            elif criteria_mode == "names":
                criteria = None
            else:
                raise SystemExit(f"unknown criteria_mode: {criteria_mode}")

            intent = {"type": "choice",
                      "instructions": "Which category should this request be routed to?",
                      "options": options}
            if criteria is not None:
                intent["criteria"] = criteria

            item = {"item_id": item_id, "state": text, "domain": domain,
                    "intent": intent, "intent_gold": domain}

            if include_extra_questions:
                item["ok"] = {"type": "noul",
                              "instructions": "Is the request clear enough to act on?"}
                item["escalate"] = {"type": "noul",
                                    "instructions": "Should a human handle this?"}
            items.append(item)

    # split by item_id hash: stable across lambdas and seeds, which is what the design needs
    for it in items:
        h = int(hashlib.sha256(it["item_id"].encode()).hexdigest()[:8], 16)
        it["split"] = "dev" if (h % 100) < 30 else "test"
    return items, rejected


CRITERIA = {
    "billing":  "a request about money: a charge, an invoice, a refund, or a payment method",
    "access":   "a request about getting in: sign-in, a password, a permission, or an account lock",
    "urgency":  "a request that needs immediate action because something is broken now or a deadline is close",
    "info":     "a request that only asks for information and needs no change to an account",
}


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the Phase I item bank (O3).")
    ap.add_argument("--size", type=int, default=932, help="frozen by O2 (Amendment 1 §A2)")
    ap.add_argument("--seed", type=int, default=20261004)
    ap.add_argument("--criteria-mode", choices=("full", "names"), default="full",
                    help="'names' weakens criteria (Amendment 1 §A4(3)); it changes what the endpoint measures")
    ap.add_argument("--include-extra-questions", action="store_true",
                    help="carry ok/escalate as noul. C2 measured the noul primitive at CHANCE, so "
                         "the default is to omit them (docs/C2_NOUL_VALIDITY.md).")
    ap.add_argument("--out", default="measurement/item_bank.jsonl")
    ap.add_argument("--manifest", default="measurement/item_bank_manifest.json")
    args = ap.parse_args()

    items, rejected = build(args.size, args.seed, args.criteria_mode, args.include_extra_questions)

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8", newline="\n") as fh:
        for it in items:
            fh.write(json.dumps(it, ensure_ascii=False) + "\n")

    # --- manifest: counts the paper must publish -------------------------------------------
    import collections
    by_dom = collections.Counter(i["domain"] for i in items)
    by_split = collections.Counter(i["split"] for i in items)
    by_opts = collections.Counter(len(i["intent"]["options"]) for i in items)
    by_dom_opts = collections.Counter((i["domain"], len(i["intent"]["options"])) for i in items)
    by_dom_split = collections.Counter((i["domain"], i["split"]) for i in items)
    chance = {n: 1.0 / n for n in by_opts}

    manifest = {
        "bank": str(out).replace("\\", "/"),
        "bank_sha256": hashlib.sha256(out.read_bytes()).hexdigest(),
        "size": len(items),
        "requested_size": args.size,
        "seed": args.seed,
        "criteria_mode": args.criteria_mode,
        "includes_ok_escalate": args.include_extra_questions,
        "gold_provenance": "CONSTRUCTION INVARIANT - not annotation. Each item is rendered from a "
                           "scenario kernel whose domain is known; no labeler is involved.",
        "ambiguity_rule": "an item for domain D is DROPPED if any rival domain's strong anchor "
                          "appears in its text. info is the residual and must contain no anchor.",
        "anchors_rejected_items": rejected,
        "counts": {
            "per_domain": dict(by_dom),
            "per_split": dict(by_split),
            "per_option_count": dict(by_opts),
            "per_domain_x_options": {f"{d}|{n}": c for (d, n), c in sorted(by_dom_opts.items())},
            "per_domain_x_split": {f"{d}|{s}": c for (d, s), c in sorted(by_dom_split.items())},
        },
        "chance_accuracy_by_option_count": chance,
        "provenance": "templates authored in scripts/build_item_bank.py. No earlier corpus. "
                      "Not generated by the pinned model.",
    }
    mp = pathlib.Path(args.manifest)
    mp.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")

    print(f"  bank     -> {out}  ({len(items)} items, {out.stat().st_size} B)")
    print(f"  sha256   -> {manifest['bank_sha256']}")
    print(f"  manifest -> {mp}  ({mp.stat().st_size} B)")
    print()
    print(f"  per domain     : {dict(by_dom)}")
    print(f"  per split      : {dict(by_split)}   (30% dev / 70% test, by item_id)")
    print(f"  per option cnt : {dict(by_opts)}   chance accuracy {[round(chance[n],4) for n in sorted(chance)]}")
    print(f"  rejected as ambiguous (mechanical rule): {rejected}")
    print()
    print(f"  domain x options:")
    for k in sorted(manifest["counts"]["per_domain_x_options"]):
        print(f"     {k:<22} {manifest['counts']['per_domain_x_options'][k]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())